#!/usr/bin/env python3
"""
Generate OpenROAD TCL script to place macros.

This creates a simple TCL script that can be sourced in OpenROAD
to set macro positions from our placement algorithm.

Usage:
    python scripts/generate_macro_placement_tcl.py --benchmark ariane133
"""

import re
import sys
import argparse
import torch
from pathlib import Path

from macro_place.loader import load_benchmark_from_dir


def generate_random_placement(benchmark, seed=42):
    """Generate random placement for demo."""
    torch.manual_seed(seed)
    placement = torch.zeros(benchmark.num_macros, 2)

    for i in range(benchmark.num_macros):
        w, h = benchmark.macro_sizes[i]
        x_min, x_max = w / 2, benchmark.canvas_width - w / 2
        y_min, y_max = h / 2, benchmark.canvas_height - h / 2

        x = torch.rand(1) * (x_max - x_min) + x_min
        y = torch.rand(1) * (y_max - y_min) + y_min

        placement[i, 0] = x
        placement[i, 1] = y

    # Respect fixed macros
    fixed_mask = benchmark.macro_fixed
    if fixed_mask.any():
        placement[fixed_mask] = benchmark.macro_positions[fixed_mask]

    return placement


def write_openroad_placement_tcl(placement, benchmark, plc, output_file):
    """
    Write OpenROAD TCL script to place macros using place_macro command.

    Args:
        placement: [num_macros, 2] tensor of (x, y) positions in microns
        benchmark: Benchmark object
        plc: PlacementCost object
        output_file: Output TCL file path
    """
    with open(output_file, 'w') as f:
        f.write("# OpenROAD Macro Placement Script\n")
        f.write("# Generated by partcl-macro-place-challenge\n")
        f.write("#\n")
        f.write("# Usage: source this file after initialize_floorplan in OpenROAD\n")
        f.write("#\n\n")

        f.write("puts \"Placing macros...\"\n\n")

        # Convert to numpy for easier access
        placement_np = placement.cpu().numpy()

        # Place each macro using place_macro command
        placed_count = 0
        for i, macro_idx in enumerate(benchmark.hard_macro_indices):
            node = plc.modules_w_pins[macro_idx]
            instance_name = node.get_name()

            # Escape brackets for OpenROAD (e.g., "block[0]" -> "block\\[0\\]")
            instance_name_escaped = instance_name.replace('[', '\\[').replace(']', '\\]')

            x, y = placement_np[i]

            # Get macro size
            w = node.get_width()
            h = node.get_height()

            # place_macro uses lower-left corner, not center
            # So convert from center to lower-left
            x_ll = x - w / 2
            y_ll = y - h / 2

            # Get orientation
            orientation = node.get_orientation() if node.get_orientation() else "R0"

            f.write(f"# Placing {instance_name}\n")
            f.write(f"place_macro \\\n")
            f.write(f"    -macro_name {{{instance_name_escaped}}} \\\n")
            f.write(f"    -location {{{x_ll:.6f} {y_ll:.6f}}} \\\n")
            f.write(f"    -orientation {orientation}\n\n")

            placed_count += 1

        f.write(f"puts \"Placed {placed_count} macros\"\n")

    print(f"✓ Generated OpenROAD placement TCL: {output_file}")
    print(f"  Placed {placed_count} macros")


def _plc_extract_group_and_index(plc_name):
    """Extract sram group prefix and flat macro index from a .plc name.

    .plc format: i_cache_subsystem/i_icache/sram_block[0].data_sram/macro_mem[K].i_ram
    Returns: (group_prefix_in_odb_format, K)

    The group prefix is everything before 'macro_mem[K]', converted to ODB naming
    (brackets to underscores, '/' to '.').  K is the flat macro index within that group.
    """
    # Extract macro_mem index
    m = re.search(r'/macro_mem\[(\d+)\]\.i_ram$', plc_name)
    if not m:
        return None, None
    macro_idx = int(m.group(1))
    prefix = plc_name[:m.start()]

    # Convert prefix to ODB format: brackets -> underscores, '/' -> '.'
    prefix = re.sub(r'\[(\d+)\]\.', r'_\1__', prefix)
    prefix = re.sub(r'\[(\d+)\]$', r'_\1__', prefix)
    prefix = prefix.replace('/', '.')

    return prefix, macro_idx


def _plc_to_odb_name(plc_name):
    """Convert a .plc hierarchical name to the Yosys-flattened ODB instance name.

    Yosys flattens generate blocks by replacing brackets and dots within
    a hierarchy level with underscores, but keeps '/' as the hierarchy separator.

    Rules (observed from ODB dumps):
      '[N].' -> '_N__'   (generate index followed by dot)
      '.'    -> '_'      (dot within a hierarchy level, NOT hierarchy separator)
      '/'    -> '/'      (hierarchy separator preserved)

    Examples:
      i_tile/gen_banks[3].mem_bank/genblk1.sram_instance
        -> i_tile/gen_banks_3__mem_bank/genblk1_sram_instance

      i_tile/gen_caches[0].i_snitch_icache/i_lookup/i_data/genblk1.fr_sp_instance0
        -> i_tile/gen_caches_0__i_snitch_icache/i_lookup/i_data/genblk1_fr_sp_instance0

      u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a
        -> u_NV_NVDLA_cbuf/u_cbuf_ram_bank0_ram0/rmod/rmod_a  (no change)
    """
    # Split by hierarchy separator first
    parts = plc_name.split('/')
    result = []
    for part in parts:
        # Handle [N]. pattern (generate index)
        part = re.sub(r'\[(\d+)\]\.', r'_\1__', part)
        # Handle [N] at end of segment
        part = re.sub(r'\[(\d+)\]$', r'_\1_', part)
        # Remaining dots within the segment become underscores
        part = part.replace('.', '_')
        result.append(part)
    return '/'.join(result)


def write_orfs_macro_placement(placement, benchmark, plc, output_file, core_area=None, use_genus_names=False):
    """
    Write macro placement in ORFS format using place_macro command.

    Uses a two-pass TCL matching strategy to handle the naming differences
    between .plc protobuf names and ODB/synthesized names:
    - .plc uses flat indexing: macro_mem[K].i_ram (K=0..N-1)
    - ODB uses generate blocks: genblk1_G__i_ram.macro_mem_M

    The mapping K -> (G,M) depends on the SRAM wrapper type (4, 3, or 1 mems
    per genblk). Instead of guessing, we match at runtime by grouping ODB
    instances by their sram block prefix and assigning linear indices.

    When use_genus_names=True, bypasses the genblk matching and uses the raw
    .plc hierarchical names directly (for Genus-mapped gate netlists which
    preserve the original hierarchy).

    When core_area is provided, proxy canvas coordinates are **scaled** to fill
    the ORFS core area (the proxy canvas and ORFS die have different dimensions).

    Args:
        placement: [num_macros, 2] tensor of (x, y) positions in microns
        benchmark: Benchmark object
        plc: PlacementCost object
        output_file: Output TCL file path
        core_area: Optional tuple (x_min, y_min, x_max, y_max) to scale+clamp positions
        use_genus_names: If True, use raw .plc names for placement (Genus netlists)
    """
    from collections import defaultdict

    placement_np = placement.cpu().numpy()

    # Compute scale factors from proxy canvas to ORFS core
    canvas_w = float(benchmark.canvas_width)
    canvas_h = float(benchmark.canvas_height)
    if core_area is not None:
        core_x_min, core_y_min, core_x_max, core_y_max = core_area
        core_w = core_x_max - core_x_min
        core_h = core_y_max - core_y_min
        scale_x = core_w / canvas_w
        scale_y = core_h / canvas_h
        offset_x = core_x_min
        offset_y = core_y_min
        print(f"  Proxy canvas: {canvas_w:.1f} x {canvas_h:.1f}")
        print(f"  ORFS core:    {core_w:.1f} x {core_h:.1f} (offset {offset_x:.1f}, {offset_y:.1f})")
        print(f"  Scale factors: {scale_x:.4f} x {scale_y:.4f}")

    # Build placement data keyed by (group_prefix, flat_macro_index)
    group_data = defaultdict(dict)  # group_prefix -> {K: (x, y, orient, plc_name)}
    direct_placements = []  # For non-Ariane designs: (odb_name, x, y, orient, plc_name)
    total_macros = 0

    for i, macro_idx in enumerate(benchmark.hard_macro_indices):
        node = plc.modules_w_pins[macro_idx]
        plc_name = node.get_name()
        x, y = placement_np[i]
        w = node.get_width()
        h = node.get_height()
        x_ll = x - w / 2
        y_ll = y - h / 2

        if core_area is not None:
            # Scale proxy coordinates to ORFS core area
            x_ll = x_ll * scale_x + offset_x
            y_ll = y_ll * scale_y + offset_y
            # Clamp to core bounds with margin for PDN channels
            # (macro sizes are physical — not scaled)
            margin = 2.0
            x_ll = max(core_x_min + margin, min(x_ll, core_x_max - w - margin))
            y_ll = max(core_y_min + margin, min(y_ll, core_y_max - h - margin))

        orientation = node.get_orientation() if node.get_orientation() else "R0"

        if use_genus_names:
            # ODB always flattens to underscores regardless of netlist source
            odb_name = _plc_to_odb_name(plc_name)
            direct_placements.append((odb_name, x_ll, y_ll, orientation, plc_name))
            total_macros += 1
        else:
            group_prefix, macro_k = _plc_extract_group_and_index(plc_name)

            if group_prefix is not None:
                group_data[group_prefix][macro_k] = (x_ll, y_ll, orientation, plc_name)
                total_macros += 1
            else:
                # Fallback: convert plc name directly to ODB name (mempool_tile, nvdla, etc.)
                odb_name = _plc_to_odb_name(plc_name)
                direct_placements.append((odb_name, x_ll, y_ll, orientation, plc_name))
                total_macros += 1

    # Post-process: enforce minimum gap between macros for PDN channel routing.
    # PDN metal5 needs ~10μm channels between macros.
    # NOTE: this modifies the submitted placement at Tier 2. A sidecar diff file
    # is written so teams can see exactly what the evaluator pushed and by how much.
    if core_area is not None:
        MIN_GAP = 12.0
        # Collect all placements into a flat list for gap enforcement.
        # Each entry: (kind, key1, key2, x, y, w, h, macro_name)
        _all = []
        for gp in group_data:
            for mk in group_data[gp]:
                x, y, orient, pn = group_data[gp][mk]
                node = None
                for ii, mi in enumerate(benchmark.hard_macro_indices):
                    if plc.modules_w_pins[mi].get_name() == pn:
                        node = plc.modules_w_pins[mi]
                        break
                if node:
                    _all.append(('group', gp, mk, x, y, node.get_width(), node.get_height(), pn))
        for idx, (odb_n, x, y, orient, pn) in enumerate(direct_placements):
            node = None
            for ii, mi in enumerate(benchmark.hard_macro_indices):
                if plc.modules_w_pins[mi].get_name() == pn:
                    node = plc.modules_w_pins[mi]
                    break
            if node:
                _all.append(('direct', idx, None, x, y, node.get_width(), node.get_height(), pn))

        # Snapshot pre-push coordinates for the sidecar diff
        _before = {entry[7]: (entry[3], entry[4]) for entry in _all}

        for iteration in range(50):
            moved = 0
            for i in range(len(_all)):
                for j in range(i + 1, len(_all)):
                    ti, ki1, ki2, xi, yi, wi, hi, pni = _all[i]
                    tj, kj1, kj2, xj, yj, wj, hj, pnj = _all[j]
                    # Check if too close (overlap + gap < MIN_GAP)
                    ox = min(xi + wi, xj + wj) - max(xi, xj)  # overlap in x
                    oy = min(yi + hi, yj + hj) - max(yi, yj)  # overlap in y
                    if ox > -MIN_GAP and oy > -MIN_GAP and (ox > 0 or oy > 0):
                        # They're too close — push apart
                        cx_i, cy_i = xi + wi / 2, yi + hi / 2
                        cx_j, cy_j = xj + wj / 2, yj + hj / 2
                        dx, dy = cx_i - cx_j, cy_i - cy_j
                        if abs(dx) >= abs(dy):
                            need = (wi + wj) / 2 + MIN_GAP
                            if abs(dx) < need:
                                shift = (need - abs(dx)) / 2 + 0.1
                                sign = 1 if dx >= 0 else -1
                                xi += sign * shift
                                xj -= sign * shift
                                moved += 1
                        else:
                            need = (hi + hj) / 2 + MIN_GAP
                            if abs(dy) < need:
                                shift = (need - abs(dy)) / 2 + 0.1
                                sign = 1 if dy >= 0 else -1
                                yi += sign * shift
                                yj -= sign * shift
                                moved += 1
                        # Clamp
                        xi = max(core_x_min + 2, min(xi, core_x_max - wi - 2))
                        yi = max(core_y_min + 2, min(yi, core_y_max - hi - 2))
                        xj = max(core_x_min + 2, min(xj, core_x_max - wj - 2))
                        yj = max(core_y_min + 2, min(yj, core_y_max - hj - 2))
                        _all[i] = (ti, ki1, ki2, xi, yi, wi, hi, pni)
                        _all[j] = (tj, kj1, kj2, xj, yj, wj, hj, pnj)
            if moved == 0:
                break

        # Compute displacements and write sidecar diff
        moved_rows = []
        for entry in _all:
            _, _, _, x_after, y_after, _, _, pn = entry
            x_before, y_before = _before[pn]
            dx = x_after - x_before
            dy = y_after - y_before
            mag = (dx * dx + dy * dy) ** 0.5
            if mag > 1e-6:
                moved_rows.append((pn, x_before, y_before, x_after, y_after, dx, dy, mag))

        if moved_rows:
            moved_rows.sort(key=lambda r: -r[7])
            diff_path = str(output_file) + ".spacing_diff.txt"
            with open(diff_path, "w") as dfh:
                dfh.write(f"# Post-push spacing adjustment (Tier 2 only, MIN_GAP={MIN_GAP}μm)\n")
                dfh.write(f"# Submitted placement had {len(moved_rows)}/{len(_all)} macros "
                          f"with <{MIN_GAP}μm clearance to a neighbour; pushed apart below.\n")
                dfh.write(f"# Columns: macro  x_before  y_before  x_after  y_after  dx  dy  |Δ|\n")
                for pn, xb, yb, xa, ya, dx, dy, mag in moved_rows:
                    dfh.write(f"{pn}\t{xb:.3f}\t{yb:.3f}\t{xa:.3f}\t{ya:.3f}\t"
                              f"{dx:+.3f}\t{dy:+.3f}\t{mag:.3f}\n")
            max_disp = moved_rows[0][7]
            mean_disp = sum(r[7] for r in moved_rows) / len(moved_rows)
            print(f"  ✓ Spacing enforcement: {iteration + 1} iters, {MIN_GAP}μm min gap, "
                  f"{len(moved_rows)}/{len(_all)} macros moved "
                  f"(mean |Δ|={mean_disp:.2f}μm, max |Δ|={max_disp:.2f}μm)")
            print(f"    sidecar diff: {diff_path}")

        # Write back
        for t, k1, k2, x, y, w, h, pn in _all:
            if t == 'group':
                _, _, orient, _ = group_data[k1][k2]
                group_data[k1][k2] = (x, y, orient, pn)
            elif t == 'direct':
                odb_n, _, _, orient, _ = direct_placements[k1]
                direct_placements[k1] = (odb_n, x, y, orient, pn)

    with open(output_file, 'w') as f:
        f.write("# Macro Placement for OpenROAD-flow-scripts\n")
        f.write("# Generated by partcl-macro-place-challenge\n")
        f.write("#\n")
        f.write("# Two-pass runtime matching: groups ODB macros by sram block prefix,\n")
        f.write("# then matches to .plc macro_mem[K] by linear index within each group.\n\n")

        # Emit placement data: dict of group_prefix -> dict of flat_index -> {x y orient}
        f.write("# Placement data: group_prefix -> flat_index -> {x y orient plc_name}\n")
        f.write("set _gpd [dict create]\n")
        for group_prefix in sorted(group_data.keys()):
            for k in sorted(group_data[group_prefix].keys()):
                x_ll, y_ll, orient, plc_name = group_data[group_prefix][k]
                f.write(f'dict set _gpd "{group_prefix}" {k} [list {x_ll:.6f} {y_ll:.6f} {orient} "{plc_name}"]\n')
        f.write("\n")

        # TCL matching logic
        f.write("""# Pass 1: Collect all block instances, grouped by sram prefix
# ODB name pattern: PREFIX.genblk1_G__i_ram.macro_mem_M
# We extract PREFIX (everything before .genblk1_), G, and M.
set _odb_groups [dict create]
set block [ord::get_db_block]
foreach inst [$block getInsts] {
    if {[$inst isBlock]} {
        set name [$inst getName]
        # Match the genblk pattern
        if {[regexp {^(.+)\\.genblk1_(\d+)__i_ram\\.macro_mem_(\d+)$} $name -> prefix genblk_idx mem_idx]} {
            dict lappend _odb_groups $prefix [list $genblk_idx $mem_idx $name]
        }
    }
}

# Pass 2: For each group, sort by (genblk_idx, mem_idx) to get linear ordering,
# then match to our .plc flat indices.
set _placed 0
set _unmatched_odb [list]
set _unmatched_plc [list]

dict for {prefix entries} $_odb_groups {
    # Sort entries by genblk_idx then mem_idx (both numeric)
    set sorted_entries [lsort -command {apply {{a b} {
        lassign $a ga ma
        lassign $b gb mb
        set ga [expr {int($ga)}]; set ma [expr {int($ma)}]
        set gb [expr {int($gb)}]; set mb [expr {int($mb)}]
        if {$ga != $gb} { return [expr {$ga - $gb}] }
        return [expr {$ma - $mb}]
    }}} $entries]

    # Assign linear index K=0,1,2,...
    set k 0
    foreach entry $sorted_entries {
        lassign $entry genblk_idx mem_idx odb_name
        if {[dict exists $_gpd $prefix] && [dict exists [dict get $_gpd $prefix] $k]} {
            lassign [dict get [dict get $_gpd $prefix] $k] x y orient plc_name
            place_macro -macro_name [list $odb_name] -location [list $x $y] -orientation $orient
            incr _placed
        } else {
            lappend _unmatched_odb "$odb_name (group=$prefix, k=$k)"
        }
        incr k
    }
}

""")

        # Direct placements for non-Ariane designs or Genus netlists
        if direct_placements:
            f.write("# Direct placements\n")
            f.write("set block [ord::get_db_block]\n" if not group_data else "")
            f.write("# Try multiple name forms to find each macro instance\n")
            f.write("proc _find_macro {block args} {\n")
            f.write("    foreach name $args {\n")
            f.write("        set inst [$block findInst $name]\n")
            f.write("        if {$inst ne \"NULL\"} { return $inst }\n")
            f.write("    }\n")
            f.write("    return NULL\n")
            f.write("}\n\n")
            for odb_name, x_ll, y_ll, orient, plc_name in direct_placements:
                # Try: 1) converted ODB name, 2) with escaped brackets, 3) raw plc name
                candidates = [odb_name]
                if plc_name != odb_name:
                    # Also try escaped-bracket version for Genus netlists
                    escaped = plc_name.replace('[', '\\[').replace(']', '\\]')
                    candidates.append(escaped)
                    candidates.append(plc_name)
                tcl_args = ' '.join(f'"{c}"' for c in candidates)
                f.write(f'# {plc_name}\n')
                f.write(f'set _inst [_find_macro $block {tcl_args}]\n')
                f.write(f'if {{$_inst ne "NULL"}} {{\n')
                # Use the inst object directly to place — avoids name escaping issues
                # Snap to manufacturing grid (10 DBU) to avoid DRT-0416 offgrid errors
                f.write(f'    set _x [ord::microns_to_dbu {x_ll:.6f}]\n')
                f.write(f'    set _y [ord::microns_to_dbu {y_ll:.6f}]\n')
                f.write(f'    set _grid [[ord::get_db_tech] getManufacturingGrid]\n')
                f.write(f'    if {{$_grid > 0}} {{ set _x [expr {{($_x / $_grid) * $_grid}}]; set _y [expr {{($_y / $_grid) * $_grid}}] }}\n')
                f.write(f'    $_inst setOrient {orient}\n')
                f.write(f'    $_inst setLocation $_x $_y\n')
                f.write(f'    $_inst setPlacementStatus FIRM\n')
                f.write(f'    incr _placed\n')
                f.write(f'}} else {{\n')
                f.write(f'    puts "WARNING: ODB instance not found: {odb_name}"\n')
                f.write(f'}}\n')
            f.write("\n")

        f.write(f'puts "Placed $_placed macros (expected {total_macros})"\n')
        f.write(f'if {{$_placed != {total_macros}}} {{\n')
        f.write(f'    puts "WARNING: Expected {total_macros} macros but placed $_placed"\n')
        f.write('    if {[llength $_unmatched_odb] > 0} {\n')
        f.write('        puts "Unmatched ODB instances:"\n')
        f.write('        foreach u $_unmatched_odb { puts "  $u" }\n')
        f.write('    }\n')
        f.write("}\n")

    n_genblk = len(group_data)
    n_direct = len(direct_placements)
    print(f"✓ Generated ORFS macro placement TCL: {output_file}")
    print(f"  {total_macros} macros ({n_genblk} sram groups, {n_direct} direct placements)")


def main():
    parser = argparse.ArgumentParser(description='Generate OpenROAD macro placement TCL')
    parser.add_argument('--benchmark', default='ariane133',
                       help='Benchmark to use (default: ariane133)')
    parser.add_argument('--output', default='output/place_macros.tcl',
                       help='Output TCL file (default: output/place_macros.tcl)')
    parser.add_argument('--seed', type=int, default=42,
                       help='Random seed (default: 42)')

    args = parser.parse_args()

    # Create output directory
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print("=" * 80)
    print("Generate OpenROAD Macro Placement TCL")
    print("=" * 80)
    print()

    # Load benchmark
    print(f"Loading benchmark: {args.benchmark}...")
    flows_dir = Path("external/MacroPlacement/Flows/NanGate45")
    benchmark_path = flows_dir / args.benchmark / "netlist" / "output_CT_Grouping"

    if not benchmark_path.exists():
        testcases_dir = Path("external/MacroPlacement/Testcases/ICCAD04")
        benchmark_path = testcases_dir / args.benchmark
        if not benchmark_path.exists():
            print(f"ERROR: Benchmark not found: {args.benchmark}")
            return 1

    benchmark, plc = load_benchmark_from_dir(str(benchmark_path))
    print(f"  ✓ Loaded {benchmark.name} ({benchmark.num_macros} macros)")
    print()

    # Generate placement (you would replace this with your algorithm)
    print(f"Generating random placement (seed={args.seed})...")
    placement = generate_random_placement(benchmark, seed=args.seed)
    print(f"  ✓ Generated placement")
    print()

    # Write TCL script
    print(f"Writing OpenROAD TCL script...")
    write_openroad_placement_tcl(placement, benchmark, plc, str(output_path))
    print()

    print("=" * 80)
    print("USAGE")
    print("=" * 80)
    print()
    print("In your OpenROAD flow, after loading LEF/netlist:")
    print()
    print(f"  source {args.output}")
    print()
    print("This will place all macros at the computed positions.")
    print("=" * 80)

    return 0


if __name__ == "__main__":
    sys.exit(main())
